Use temporary name for netdevice when moving in/out of NS
containernetworking/plugins pull request #1002
Opened 2024-01-23 12:35 UTC by adrianchiris

Today, it is not possible to use host-device CNI to move a
host device to container namespace if a device already exists
in that namespace.

e.g when a delegate plugin (such as multus) is used to provide
multiple networks to a container, CNI Add call will fail if
the targeted host device name already exists in container network
namespace.

to overcome this, we use a temporary name for the interface before
moving it in/out of container network namespace.

2024-01-31 08:10 UTC, adrianchiris commented
@squeed @dcbw could you take a look a this one :)

2024-03-11 16:02 UTC, s1061123 requested changes
@adrianchiris sorry to review this. It looks good to me almost code. Regarding error handling, I added one comment. could you please take a look into it? Thanks!

2024-03-12 09:58 UTC, adrianchiris commented on plugins/main/host-device/host-device.go
> +		return nil, fmt.Errorf("failed to rename device %q to temporary name: %v", hostDevName, err)
added logic to restore netdev:

- bring back to host namespace
- retore netdev name
- restore link status

2024-03-12 11:09 UTC, adrianchiris commented
@s1061123 thx for reviewing. comment addressed.

2024-03-12 11:51 UTC, s1061123 approved these changes
LGTM'ed!

2024-03-12 11:51 UTC, merged